version: "2"

services:

# No hace falta exponer el puerto. simplemente mete 172.20.0.3	ecoembes.local en /etc/hosts
  front:
    build: Dockerfiles/php7-apache2
    volumes:
      - ./:/var/www/html

 # https://www.drupal.org/node/2754539 --> implementar esto
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker-runtime/mysql:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    links:
        - mysql:db
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_POST_MAX_SIZE: 1G
      UPLOAD_SIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
      - "8002:80"