version: "2"

services:

  front:
    build: Dockerfiles/php7-apache2
    volumes:
      - ./:/var/www/html
    labels:
      - "traefik.frontend.rule=Host:aed.localhost"

 # https://www.drupal.org/node/2754539 --> implementar esto
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker-runtime/mysql:/var/lib/mysql
    ports:
      - "3308:3306"

  pma:
    image: phpmyadmin/phpmyadmin
    links:
        - mysql:db
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_POST_MAX_SIZE: 1G
      UPLOAD_SIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - "traefik.frontend.rule=Host:aed-db.localhost"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8002:8025"
