plugin.plugin_configuration.facets_summary_processor.show_summary:
  type: config_object

plugin.plugin_configuration.facets_summary_processor.show_count:
  type: config_object

plugin.plugin_configuration.facets_summary_processor.hide_when_not_rendered:
  type: config_object

plugin.plugin_configuration.facets_summary_processor.show_text_when_empty:
  type: mapping
  label: 'No results behavior'
  mapping:
    text:
      type: text_format
      label: 'The text to show when there is no current search'
