<?php

define('PAYPAL_BILLING_PLAN_TYPE_FIXED', 'fixed');

/**
 * Implements hook_help().
 * @param array $attachments
 */
function paypal_sdk_page_attachments(array &$attachments) {
  #Since libraries-extend DOES NOT WORK on modules we need to attach our minimal css
  $attachments['#attached']['library'][] = 'paypal_sdk/toolbar';
}


function paypal_sdk_theme() {
  return [
    'plan_list_tables' => [
      'template' => 'plan-list-tables',
      'variables' => ['tables' => NULL],
    ],
  ];
}
