<?php

use Drupal\Core\Render\BubbleableMetadata;
use Drupal\user\Entity\User;

function aed_user_token_info() {
  return array(
    'tokens' => [
      'site' => [
        'login-url-or-user-url' => [
          'name' => t("User URL or login page"),
          'description' => t("User URL or login page."),
        ]
      ]
    ],
  );
}


/**
 * Implements hook_tokens().
 */
function aed_user_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = array();

  if ($type == 'site') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'login-url-or-user-url':

          $currentUser = \Drupal::currentUser();

          if ($currentUser->isAnonymous()) {
            /** @var \Drupal\Core\GeneratedUrl $result */
            $result = \Drupal::url('user.page', [], [], TRUE);
            $bubbleable_metadata->addCacheableDependency($result);
            $replacements[$original] = $result->getGeneratedUrl();
          }
          else {
            $account = User::load($currentUser->id());
            $replacements[$original] = $account->url('edit-form', []);
          }


          break;
      }
    }
  }

  return $replacements;
}
