<?php

/**
 * @file
 * Contains linked_image_field.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function linked_image_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the linked_image_field module.
    case 'help.page.linked_image_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

