features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://isologo-aed-black-145x41_0.png'
favicon:
  use_default: 0
  path: themes/custom/aed_th/images/favicon.png
  mimetype: image/png
