_core:
  default_config_hash: 2TnP0TViNExHGuA7Cdr4L3uxhYGNzKyL0XnoAhtSHMQ
form_ids:
  - 'comment_*'
  - user_login_form
  - user_pass
  - user_register_form
  - 'contact_message_*'
  - 'webform_*'
excluded_form_ids:
  - ''
show_form_ids: false
