_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
definitions:
  standard__front_page:
    weight: -41
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
  user__page:
    menu_name: main
    parent: ''
    weight: -48
    expanded: false
    enabled: true
  user__logout:
    menu_name: main
    parent: ''
    weight: -49
    expanded: false
    enabled: true
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: -50
    expanded: false
    enabled: false
