<?php

/**
 * Implements hook_theme().
 */
function facets_summary_theme($existing, $type, $theme, $path) {
  return [
    'facets_summary' => [
      'variables' => [
        'count' => [],
        'items' => [],
      ],
    ],
    'facets_summary_count' => [
      'variables' => [
        'count' => NULL,
      ],
    ],
    'facets_summary_facet' => [
      'render element' => 'elements',
      'variables' => [
        'label' => NULL,
        'separator' => '',
        'items' => [],
        'facet_id' => NULL,
        'facet_admin_label' => NULL,
      ],
    ],
    'facets_summary_facet_result' => [
      'variables' => [
        'label' => NULL,
        'show_count' => FALSE,
        'count' => NULL,
        'facet_id' => NULL,
      ],
    ],
    'facets_summary_empty' => [
      'variables' => [
        'message' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function facets_source_summary_theme_suggestions_facets_source_summary_facet(array $variables) {
  // Add suggestions as: facets-source-summary-facet--{facet_id}.
  return ['facets_source_summary_facet__' . $variables['facet_id']];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function facets_source_summary_theme_suggestions_facets_source_summary_facet_result(array $variables) {
  // Add suggestions as: facets-source-summary-facet-result--{facet_id}.
  return [$variables['theme_hook_original'] . '__' . $variables['facet_id']];
}
